import { actionLabel, causeLabel, formatDateTime, formatMoney } from '../lib/format.js'

function Step({ n, children }) {
  return (
    <div className="flex gap-3">
      <div className="flex h-7 w-7 flex-none items-center justify-center rounded-full bg-blue-600 text-xs font-semibold text-white">
        {n}
      </div>
      <div className="pb-6 text-slate-700">{children}</div>
    </div>
  )
}

function fundingNarrative(payment) {
  const trace = payment.allocator_stage_traces?.[0]?.find((t) => t.stage === 'funding_window')
  if (!trace || trace.skipped) return null
  const match = trace.output_summary.match(/confidence=([\d.]+) used_fallback=(True|False)/)
  if (!match) return null
  const usedFallback = match[2] === 'True'
  return usedFallback
    ? "We don't have enough reliable payment history for this account yet, so instead of guessing, we wait using a documented safe pattern (a day, then three days, then a week)."
    : `Based on this account's past payment history, we estimate it's usually funded around this time of the month - so we aim the retry near then (confidence ${match[1]}).`
}

export default function StoryView({ payment, isLive = false }) {
  if (!payment) return null
  const decision = payment.allocator_decisions?.[0]
  const explanation = payment.explanation
  const outcome = payment.allocator
  const funding = fundingNarrative(payment)

  return (
    <div className="grid gap-6 md:grid-cols-3">
      <div className="md:col-span-2 rounded-lg border border-slate-200 bg-white p-6">
        <Step n={1}>
          A recurring payment of <strong>{formatMoney(payment.amount)}</strong> failed on {formatDateTime(payment.failure_time)}.
        </Step>
        <Step n={2}>
          Why: <strong>{causeLabel(payment.cause)}</strong>.{' '}
          {explanation ? explanation.reasoning_plain : 'This is fixable by trying again at the right time.'}
        </Step>
        {funding && <Step n={3}>{funding}</Step>}
        <Step n={funding ? 4 : 3}>
          By law, we're allowed at most <strong>3 retry attempts</strong> for this payment, and never during a bank's busy hours.
        </Step>
        {decision && (
          <Step n={funding ? 5 : 4}>
            Decision: <strong>{actionLabel(decision.action)}</strong>.{' '}
            {decision.scheduled_at && (
              <>
                Next attempt scheduled for <strong>{formatDateTime(decision.scheduled_at)}</strong>.
              </>
            )}
          </Step>
        )}
        {outcome ? (
          <Step n={funding ? 6 : 5}>
            Outcome: {outcome.recovered ? (
              <span className="font-medium text-emerald-700">Payment recovered - {formatMoney(outcome.amount_recovered)} collected.</span
              >
            ) : outcome.stopped_early ? (
              <span className="font-medium text-slate-600">Stopped without spending an attempt - this could not have been fixed by retrying.</span>
            ) : (
              <span className="font-medium text-rose-600">Not recovered within the 3-attempt budget.</span>
            )}
            {' '}({outcome.attempts_spent} of 3 attempts used)
          </Step>
        ) : (
          <Step n={funding ? 6 : 5}>
            <span className="text-slate-500">
              No outcome to show here - a live decision only classifies and decides, it doesn't simulate whether a debit actually
              succeeds (that stays exclusively in the fixed Batch Results study, PRD Sec 5.1).
            </span>
          </Step>
        )}
      </div>

      <div className="space-y-4">
        {explanation && (
          <div className="rounded-lg border border-slate-200 bg-white p-4">
            <h3 className="text-xs font-semibold uppercase tracking-wide text-slate-400">Customer notification</h3>
            <p className="mt-2 text-sm text-slate-700">{explanation.notification_copy_en}</p>
            <p className="mt-2 text-xs text-slate-400">
              {explanation.generated_by === 'llm' ? 'Generated by the LLM explanation layer (Stage 7)' : 'Template fallback (LLM unavailable for this payment)'}
            </p>
          </div>
        )}
        <div className="rounded-lg border border-slate-200 bg-white p-4">
          <h3 className="text-xs font-semibold uppercase tracking-wide text-slate-400">{isLive ? 'This just ran, live' : 'This is a simulation'}</h3>
          <p className="mt-2 text-sm text-slate-500">
            {isLive
              ? "This decision was computed just now by the real pipeline running on this machine - not a canned demo. It never touches the real Razorpay API (see Live Simulator tab)."
              : "This payment was generated to match Razorpay's real error-object schema, not a live transaction. See the Batch Results tab for the outcome model and honesty notes."}
          </p>
        </div>
      </div>
    </div>
  )
}
