import { actionLabel, causeLabel, formatDateTime, formatMoney } from '../lib/format.js'

function Step({ n, children }) {
  return (
    <div className="flex gap-3">
      <div className="flex h-7 w-7 flex-none items-center justify-center rounded-full bg-blue-600 text-xs font-semibold text-white">
        {n}
      </div>
      <div className="pb-6 text-slate-700">{children}</div>
    </div>
  )
}

export default function StoryView({ payment }) {
  if (!payment) return null
  const decision = payment.allocator_decisions?.[0]
  const explanation = payment.explanation
  const outcome = payment.allocator

  return (
    <div className="grid gap-6 md:grid-cols-3">
      <div className="md:col-span-2 rounded-lg border border-slate-200 bg-white p-6">
        <Step n={1}>
          A recurring payment of <strong>{formatMoney(payment.amount)}</strong> failed on {formatDateTime(payment.failure_time)}.
        </Step>
        <Step n={2}>
          Why: <strong>{causeLabel(payment.cause)}</strong>.{' '}
          {explanation ? explanation.reasoning_plain : 'This is fixable by trying again at the right time.'}
        </Step>
        <Step n={3}>
          By law, we're allowed at most <strong>3 retry attempts</strong> for this payment, and never during a bank's busy hours.
        </Step>
        {decision && (
          <Step n={4}>
            Decision: <strong>{actionLabel(decision.action)}</strong>.{' '}
            {decision.scheduled_at && (
              <>
                Next attempt scheduled for <strong>{formatDateTime(decision.scheduled_at)}</strong>.
              </>
            )}
          </Step>
        )}
        <Step n={5}>
          Outcome: {outcome.recovered ? (
            <span className="font-medium text-emerald-700">Payment recovered - {formatMoney(outcome.amount_recovered)} collected.</span>
          ) : outcome.stopped_early ? (
            <span className="font-medium text-slate-600">Stopped without spending an attempt - this could not have been fixed by retrying.</span>
          ) : (
            <span className="font-medium text-rose-600">Not recovered within the 3-attempt budget.</span>
          )}
          {' '}({outcome.attempts_spent} of 3 attempts used)
        </Step>
      </div>

      <div className="space-y-4">
        {explanation && (
          <div className="rounded-lg border border-slate-200 bg-white p-4">
            <h3 className="text-xs font-semibold uppercase tracking-wide text-slate-400">Customer notification</h3>
            <p className="mt-2 text-sm text-slate-700">{explanation.notification_copy_en}</p>
            <p className="mt-3 border-t border-slate-100 pt-3 text-sm text-slate-500 italic">{explanation.notification_copy_hinglish}</p>
            <p className="mt-2 text-xs text-slate-400">
              {explanation.generated_by === 'llm' ? 'Generated by the LLM explanation layer (Stage 7)' : 'Template fallback (LLM unavailable for this payment)'}
            </p>
          </div>
        )}
        <div className="rounded-lg border border-slate-200 bg-white p-4">
          <h3 className="text-xs font-semibold uppercase tracking-wide text-slate-400">This is a simulation</h3>
          <p className="mt-2 text-sm text-slate-500">
            This payment was generated to match Razorpay's real error-object schema, not a live transaction. See the Batch Results tab
            for the outcome model and honesty notes.
          </p>
        </div>
      </div>
    </div>
  )
}
